#:schema node_modules/wrangler/config-schema.json
name = "rpc-protobuf-client"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

services = [
	{ binding = "RPC_SERVER", service = "rpc-protobuf-server" }
]
